### ISSUE TITLE
Cannot find module 'es-abstract/2023/CreateDataProperty'

### ISSUE THREAD

**Issue by luveshsadhwani** [es-shims/Object.getOwnPropertyDescriptors#50]
Hi there,

In a recent update of your patch version from 2.1.6 to 2.1.7, a different minor version of es-abstract was used. This resulted in the following issue for one of our services

`2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]/app/node_modules/object.getownpropertydescriptors/implementation.js:1
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]Error: Cannot find module 'es-abstract/2023/CreateDataProperty'
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]Require stack:
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]- /app/node_modules/object.getownpropertydescriptors/implementation.js
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]- /app/node_modules/object.getownpropertydescriptors/index.js
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]- /app/node_modules/util.promisify/implementation.js
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]- /app/node_modules/util.promisify/index.js
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]- /app/node_modules/bull/lib/queue.js
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]- /app/node_modules/bull/index.js
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]- /app/bullQueues.js
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]- /app/app.js
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]- /app/index.js
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]    at Object.<anonymous> (/app/node_modules/object.getownpropertydescriptors/implementation.js:3:26)
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]  code: 'MODULE_NOT_FOUND',
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]  requireStack: [
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]    '/app/node_modules/object.getownpropertydescriptors/implementation.js',
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]    '/app/node_modules/object.getownpropertydescriptors/index.js',
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]    '/app/node_modules/util.promisify/implementation.js',
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]    '/app/node_modules/util.promisify/index.js',
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]    '/app/node_modules/bull/lib/queue.js',
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]    '/app/node_modules/bull/index.js',
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]    '/app/bullQueues.js',
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]    '/app/app.js',
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]    '/app/index.js'
2023-09-08T05:57:27Z app[6e82d0df396587] sin [info]  ]`

I believe when running npm install it will use the latest patch version, but because our dependency was locked at 1.21.2, this became a breaking change.

**Comment by ljharb** [comment]
I'm a bit confused; `object.getownpropertydescriptors` requires es-abstract `^1.22.1`, so it shouldn't be possible to install v1.21.2, as that version isn't compatible.

In other words, if you actually are using npm, and npm install whatever is using util.promisify and object.getownpropertydescriptors, you'll get es-abstract v1.22.1 or higher.
